name: Metrics

on:
  schedule:
    - cron: "0 7 * * *"   # cada d√≠a 07:00 UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: SebiGitHub
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, activity, repositories
          config_timezone: Europe/Madrid
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_from: 200

